version: '3'

services:
  mysql:
    image: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/sql
      - ./mysqld.cnf:/etc/sql/conf.d/mysqld.cnf
      - ./logs:/var/log/sql
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_VOLUME}:/data
