version: '3'

services:
  mysql:
    image: "mysql:5.7.10"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/sql
      - ./mysqld.cnf:/etc/sql/conf.d/mysqld.cnf
      - ./logs:/var/log/sql
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_VOLUME}:/data
